# version: "3.9"

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb_nestjs_rrhh
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - 27019:27017
    volumes:
      - ./mongo-data:/data/db
